version: '3.7'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5428:5432"
    volumes:
      - PG_DATA:/var/lib/postgresql/data


volumes:
  PG_DATA:
  SERVER_DATA:


